version: "3.5"

services:
  rjserver:
    build: .
    expose:
      - "80"
      - "443"
    # ports:
      # - "80:80"
      # - "443:443"
    networks:
      - rjnet
    restart: always
    volumes:
      - "./data:/app/data"
      - "./projects:/app/projects"
      - "./static:/app/static"
      - "./templates:/app/templates"

  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    networks:
      - rjnet
    restart: always
    volumes:
      - "./nginx/logs:/var/log/nginx"

networks:
  rjnet:
    name: rjnewsite_default

